---
title: "SPC_20190401"
output: html_document
---
## Start Code

```{r warning=FALSE}
# Import libraries
library("readxl")
library("dplyr")
library("readr")
library("ggplot2")
library("tidyr")
library("plotly")
library("shiny")
library("shinyjs")
library("colorspace")
library("RColorBrewer")
```


```{r warning=FALSE}
#Import raw data

raw <- read_xlsx("SampleData-with-timestamp-24hrs.xlsx")

raw$TimeStamp_24 <- as.POSIXct(raw$TimeStamp_24, format ='%d/%m/%Y %H:%M:%S')

```

```{r}
spc <- raw %>% 
  rename(
    TestItem = `Test Item`,
    TestValue = `Test Value`,
    InspectionMethod = `Inspection Method`,
    TimeStamp = TimeStamp_24
  )

new_ds <- subset(spc, is.na(spc$TestValue) == FALSE)
dataset0 <- subset(new_ds, is.na(new_ds$TimeStamp) == FALSE) ## Cleaned Dataset
```

```{r}
rulevector <- c("Rule1", "Rule2", "Rule3", "Rule4", "Rule5", "Rule6", "Rule7", "Rule8")
dataset0[ , rulevector] <- NA
```

```{r}
dataset1 <- dataset0 %>%
   arrange(TimeStamp)
```

```{r}
#temp_f<-file("cleaned_ds_0402.csv",encoding="UTF-8")
#write.csv(dataset1, file = temp_f, row.names=FALSE)
```

```{r}
ds <- dataset1

uniq_process <- unique(ds$Process)
uniq_item <- unique(ds$TestItem)
uniq_station <- unique(ds$Station)
```

## UI
```{r}
ui <- fluidPage(
  
  # Application title
  titlePanel("SPC Shiny Visualization"),
  
  fluidRow(
    
    column(3, wellPanel(
      selectInput("process", "Select Process:", 
                  choices=uniq_process)
    )),
    
    column(3, wellPanel(
      # This outputs the dynamic UI component
      uiOutput("item_Selector")
    )),
    
    column(3, wellPanel(
      # This outputs the dynamic UI component
      uiOutput("station_Selector")
    ))
  ),
  
  mainPanel(
    tags$style(type="text/css",
               ".shiny-output-error { visibility: hidden; }",
               ".shiny-output-error:before { visibility: hidden; }"),
    tags$br(),
    plotlyOutput("R1_plot"),
    tags$br(),
    plotlyOutput("R2_plot"),
    tags$br(),
    plotlyOutput("R3_plot"),
    tags$br(),
    plotlyOutput("R4_plot"),
    tags$br(),
    plotlyOutput("R5_plot"),
    tags$br(),
    plotlyOutput("R6_plot"),
    tags$br(),
    plotlyOutput("R7_plot"),
    tags$br(),
    plotlyOutput("R8_plot"),
    tags$br()
  )
)
```


## Server
```{r}
server <- function(input, output){
  
  ## Create 'item' selector
  output$item_Selector <- renderUI({
    selectInput("item", "Select Item", unique((subset(ds, ds$Process == input$process))$TestItem))
  })
  
  ## Create 'station' selector
  output$station_Selector <- renderUI({
    selectInput("station", "Select Station", unique((subset(ds, ds$Process == input$process & ds$TestItem == input$item))$Station))
  })
  
  ## R1_plot
  output$R1_plot <- renderPlotly({
    choice <- subset(ds, ds$Process == input$process & ds$TestItem == input$item & ds$Station == input$station)
    
    # Nelson's QC rule 1: detect values outside + or -3 sd
    nelsonr1 <- function(x, m = mean(x), s = sd(x)) {
      which(abs((x - m) / s) >= 3)
    }
    
    # R1
    rule1 <- nelsonr1(choice$TestValue)
    for (rowindex in rule1){
      choice[rowindex,9] <- "Violation" 
    }
    choice[c("Rule1")][is.na(choice[c("Rule1")])] <- "Good"

    ## Stats
    avg <- mean(choice$TestValue)
    sig3 <- 3*sd(choice$TestValue)
    sig2 <- 2*sd(choice$TestValue)
    sig <- sd(choice$TestValue)
    
    p1 <- ggplot(choice,aes(x=TimeStamp,y=TestValue))+
      
      scale_colour_manual(values = c("Violation" = "red", "Good" = "blue"))+
      
      geom_hline(yintercept = c(sig3 +avg,-sig3 +avg),colour='red')+
      
      geom_hline(yintercept = c(sig2+avg,sig+avg,-sig+avg,-sig2+avg), linetype='dashed')+
      
      geom_hline(yintercept = avg,colour='green')+
      
      geom_line(colour = 'grey')+
      
      geom_point(aes(colour=Rule1))
    
    ggplotly(p1)
    
  })
  
  ## R2_plot
  output$R2_plot <- renderPlotly({
    choice <- subset(ds, ds$Process == input$process & ds$TestItem == input$item & ds$Station == input$station)
    
    # Nelson's QC rule 2: detect runs of >= 9 points on the same side of the mean
    nelsonr2 <- function(x, m = mean(x), minrun = 9) {
      n <- length(x)
      counts <- sign(x - m)
      result <- counts
      for (runlength in 2:minrun)
        result <- result + c(counts[runlength:n], rep(0, runlength - 1))
      which(abs(result) >= minrun)
    }
    
    # R2
    rule2 <- nelsonr2(choice$TestValue)
    for (rowindex in rule2){
      choice[rowindex,10] <- "Violation" 
    }
    choice[c("Rule2")][is.na(choice[c("Rule2")])] <- "Good"
    
    
    ## Stats
    avg <- mean(choice$TestValue)
    sig3 <- 3*sd(choice$TestValue)
    sig2 <- 2*sd(choice$TestValue)
    sig <- sd(choice$TestValue)
    
    p2 <- ggplot(choice,aes(x=TimeStamp,y=TestValue))+
      
      scale_colour_manual(values = c("Violation" = "red", "Good" = "blue"))+
      
      geom_hline(yintercept = c(sig3 +avg,-sig3 +avg),colour='red')+
      
      geom_hline(yintercept = c(sig2+avg,sig+avg,-sig+avg,-sig2+avg), linetype='dashed')+
      
      geom_hline(yintercept = avg,colour='green')+
      
      geom_line(colour = 'grey')+
      
      geom_point(aes(colour=Rule2))
    
    ggplotly(p2)
    
  })
  
  ## R3_plot
  output$R3_plot <- renderPlotly({
    choice <- subset(ds, ds$Process == input$process & ds$TestItem == input$item & ds$Station == input$station)
    
    # Nelson's QC rule 3: detect strict increase or decrease in >= 6 points in a row Between 6 points you have 5 instances of increasing or decreasing. Therefore minrun - 1.
    nelsonr3 <- function(x, minrun = 6) {
      n <- length(x)
      signs <- sign(c(x[-1], x[n]) - x)
      counts <- signs
      for (rl in 2:(minrun - 1)) {
        counts <- counts + c(signs[rl:n], rep(0, rl - 1))
      }
      which(abs(counts) >= minrun - 1)
    }
    
    # R3
    rule3 <- nelsonr3(choice$TestValue)
    for (rowindex in rule3){
      choice[rowindex,11] <- "Violation" 
    }
    choice[c("Rule3")][is.na(choice[c("Rule3")])] <- "Good"
    
    
    ## Stats
    avg <- mean(choice$TestValue)
    sig3 <- 3*sd(choice$TestValue)
    sig2 <- 2*sd(choice$TestValue)
    sig <- sd(choice$TestValue)
    
    p3 <- ggplot(choice,aes(x=TimeStamp,y=TestValue))+
      
      scale_colour_manual(values = c("Violation" = "red", "Good" = "blue"))+
      
      geom_hline(yintercept = c(sig3 +avg,-sig3 +avg),colour='red')+
      
      geom_hline(yintercept = c(sig2+avg,sig+avg,-sig+avg,-sig2+avg), linetype='dashed')+
      
      geom_hline(yintercept = avg,colour='green')+
      
      geom_line(colour = 'grey')+
      
      geom_point(aes(colour=Rule3))
    
    ggplotly(p3)
    
  })
  
  ## R4_plot
  output$R4_plot <- renderPlotly({
    choice <- subset(ds, ds$Process == input$process & ds$TestItem == input$item & ds$Station == input$station)
    
    # Nelson's QC rule 4: 14 points in a row alternating in direction from the mean, or 14 points in a row alternating in increase and decrease
    nelsonr4 <- function(x, m = mean(x), minrun = 14, directing_from_mean = FALSE) {
      n <- length(x)
      if (directing_from_mean == TRUE) {
        signs <- sign(x - m)
      } else {
        signs <- sign(c(x[-1],x[n]) - x)
      }
      counts <- signs
      fac <- -1
      for (rl in 2:minrun) {
        counts <- counts + fac * c(signs[rl:n], rep(0, rl - 1))
        fac <- -fac
      }
      counts <- abs(counts)
      which(counts >= minrun)
    }
    
    # R4
    rule4 <- nelsonr4(choice$TestValue)
    for (rowindex in rule4){
      choice[rowindex,12] <- "Violation" 
    }
    choice[c("Rule4")][is.na(choice[c("Rule4")])] <- "Good"
    
    
    ## Stats
    avg <- mean(choice$TestValue)
    sig3 <- 3*sd(choice$TestValue)
    sig2 <- 2*sd(choice$TestValue)
    sig <- sd(choice$TestValue)
    
    p4 <- ggplot(choice,aes(x=TimeStamp,y=TestValue))+
      
      scale_colour_manual(values = c("Violation" = "red", "Good" = "blue"))+
      
      geom_hline(yintercept = c(sig3 +avg,-sig3 +avg),colour='red')+
      
      geom_hline(yintercept = c(sig2+avg,sig+avg,-sig+avg,-sig2+avg), linetype='dashed')+
      
      geom_hline(yintercept = avg,colour='green')+
      
      geom_line(colour = 'grey')+
      
      geom_point(aes(colour=Rule4))
    
    ggplotly(p4)
    
  })
  
  ## R5_plot
  output$R5_plot <- renderPlotly({
    choice <- subset(ds, ds$Process == input$process & ds$TestItem == input$item & ds$Station == input$station)
    
    # Nelson's QC rule 5: two out of 3 >2 sd from mean in the same direction
    nelsonr5 <- function(x, m = mean(x), s = sd(x), minrun = 3) {
      n <- length(x)
      pos <- 1 * ((x - m) / s > 2)
      neg <- 1 * ((x - m) / s < -2)
      poscounts <- pos
      negcounts <- neg
      for (rl in 2:minrun) {
        poscounts <- poscounts + c(pos[rl:n], rep(0, rl - 1))
        negcounts <- negcounts + c(neg[rl:n], rep(0, rl - 1))
      }
      counts <- apply(cbind(poscounts, negcounts), 1, max)
      which(counts >= minrun -1)
    }
    
    # R5
    rule5 <- nelsonr5(choice$TestValue)
    for (rowindex in rule5){
      choice[rowindex,13] <- "Violation" 
    }
    choice[c("Rule5")][is.na(choice[c("Rule5")])] <- "Good"
    
    
    ## Stats
    avg <- mean(choice$TestValue)
    sig3 <- 3*sd(choice$TestValue)
    sig2 <- 2*sd(choice$TestValue)
    sig <- sd(choice$TestValue)
    
    p5 <- ggplot(choice,aes(x=TimeStamp,y=TestValue))+
      
      scale_colour_manual(values = c("Violation" = "red", "Good" = "blue"))+
      
      geom_hline(yintercept = c(sig3 +avg,-sig3 +avg),colour='red')+
      
      geom_hline(yintercept = c(sig2+avg,sig+avg,-sig+avg,-sig2+avg), linetype='dashed')+
      
      geom_hline(yintercept = avg,colour='green')+
      
      geom_line(colour = 'grey')+
      
      geom_point(aes(colour=Rule5))
    
    ggplotly(p5)
    
  })
  
  ## R6_plot
  output$R6_plot <- renderPlotly({
    choice <- subset(ds, ds$Process == input$process & ds$TestItem == input$item & ds$Station == input$station)
    
    # Nelson's QC rule 6: four out of five > 1 sd from mean in the same direction
    nelsonr6 <- function(x, m = mean(x), s = sd(x), minrun = 5) {
      n <- length(x)
      pos <- 1 * ((x - m) / s > 1)
      neg <- 1 * ((x - m) / s < -1)
      poscounts <- pos
      negcounts <- neg
      for (rl in 2:minrun) {
        poscounts <- poscounts + c(pos[rl:n], rep(0, rl - 1))
        negcounts <- negcounts + c(neg[rl:n], rep(0, rl - 1))
      }
      counts <- apply(cbind(poscounts, negcounts), 1, max)
      which(counts >= minrun - 1)
    }
    
    # R6
    rule6 <- nelsonr6(choice$TestValue)
    for (rowindex in rule6){
      choice[rowindex,14] <- "Violation" 
    }
    choice[c("Rule6")][is.na(choice[c("Rule6")])] <- "Good"
    
    
    ## Stats
    avg <- mean(choice$TestValue)
    sig3 <- 3*sd(choice$TestValue)
    sig2 <- 2*sd(choice$TestValue)
    sig <- sd(choice$TestValue)
    
    p6 <- ggplot(choice,aes(x=TimeStamp,y=TestValue))+
      
      scale_colour_manual(values = c("Violation" = "red", "Good" = "blue"))+
      
      geom_hline(yintercept = c(sig3 +avg,-sig3 +avg),colour='red')+
      
      geom_hline(yintercept = c(sig2+avg,sig+avg,-sig+avg,-sig2+avg), linetype='dashed')+
      
      geom_hline(yintercept = avg,colour='green')+
      
      geom_line(colour = 'grey')+
      
      geom_point(aes(colour=Rule6))
    
    ggplotly(p6)
    
  })
  
  ## R7_plot
  output$R7_plot <- renderPlotly({
    choice <- subset(ds, ds$Process == input$process & ds$TestItem == input$item & ds$Station == input$station)
    
    # Nelson's QC rule 7: >= 15 points in a row within 1 sd from the mean
    nelsonr7 <- function(x, m = mean(x), s = sd(x), minrun = 15) {
      n <- length(x)
      within <- 1 * (abs((x - m) / s) < 1)
      counts <- within
      for (rl in 2:minrun)
        counts <- counts + c(within[rl:n], rep(0, rl - 1))
      which(counts >= minrun)
    }
    
    # R7
    rule7 <- nelsonr7(choice$TestValue)
    for (rowindex in rule7){
      choice[rowindex,15] <- "Violation" 
    }
    choice[c("Rule7")][is.na(choice[c("Rule7")])] <- "Good"
    
    
    ## Stats
    avg <- mean(choice$TestValue)
    sig3 <- 3*sd(choice$TestValue)
    sig2 <- 2*sd(choice$TestValue)
    sig <- sd(choice$TestValue)
    
    p7 <- ggplot(choice,aes(x=TimeStamp,y=TestValue))+
      
      scale_colour_manual(values = c("Violation" = "red", "Good" = "blue"))+
      
      geom_hline(yintercept = c(sig3 +avg,-sig3 +avg),colour='red')+
      
      geom_hline(yintercept = c(sig2+avg,sig+avg,-sig+avg,-sig2+avg), linetype='dashed')+
      
      geom_hline(yintercept = avg,colour='green')+
      
      geom_line(colour = 'grey')+
      
      geom_point(aes(colour=Rule7))
    
    ggplotly(p7)
    
  })
  
  ## R8_plot
  output$R8_plot <- renderPlotly({
    choice <- subset(ds, ds$Process == input$process & ds$TestItem == input$item & ds$Station == input$station)
    
    # Nelson's QC rule 8: >= 8 points in a row all outside the m + -1s range
    nelsonr8 <- function(x, m = mean(x), s = sd(x), minrun = 8) {
      n <- length(x)
      outofrange <- 1 * (abs((x - m) / s) > 1)
      counts <- outofrange
      for (rl in 2:minrun)
        counts <- counts + c(outofrange[rl:n], rep(0, rl - 1))
      which(counts >= minrun)
    }
    
    # R8
    rule8 <- nelsonr8(choice$TestValue)
    for (rowindex in rule8){
      choice[rowindex,16] <- "Violation" 
    }
    choice[c("Rule8")][is.na(choice[c("Rule8")])] <- "Good"
    
    
    ## Stats
    avg <- mean(choice$TestValue)
    sig3 <- 3*sd(choice$TestValue)
    sig2 <- 2*sd(choice$TestValue)
    sig <- sd(choice$TestValue)
    
    p8 <- ggplot(choice,aes(x=TimeStamp,y=TestValue))+
      
      scale_colour_manual(values = c("Violation" = "red", "Good" = "blue"))+
      
      geom_hline(yintercept = c(sig3 +avg,-sig3 +avg),colour='red')+
      
      geom_hline(yintercept = c(sig2+avg,sig+avg,-sig+avg,-sig2+avg), linetype='dashed')+
      
      geom_hline(yintercept = avg,colour='green')+
      
      geom_line(colour = 'grey')+
      
      geom_point(aes(colour=Rule8))
    
    ggplotly(p8)
    
  })
  
}
```

## App
```{r warning=FALSE}
shinyApp(ui = ui, server = server)
```


## End
